# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [1]:
s="Hi there Sam!"
s=s.split()
print(s);


['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [2]:
planet = "Earth"
diameter = 12742
"print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));"

"print( 'The diameter of {} is {} kilometers.' .format(planet,diameter));"

## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [15]:
d['k1'][3]['tricky'][3]['target'][3]
Out[1]: 'hello'

NameError: name 'd' is not defined

# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [4]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)


An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)


An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [6]:
import numpy as np
"array=np.arange(20,35,2)"
print("Array of all the even integers from 20 to 35")
print(array)
"np.arange(0,9).reshape((3,3))"

Array of all the even integers from 20 to 35
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
"np.arange(0,9).reshape((3,3))"

'np.arange(0,9).reshape((3,3))'

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [8]:
"a = np.array([[1, 2, 3]])"
"b = np.array([[4, 5, 6]])"
"np.concatenate((a, b), axis=0)"
"array([[1, 2, 3],"
"       [4, 5, 6]])"
"np.concatenate((a, b.T), axis=1)"
"array([[1, 2, 5],"
"       [3, 4, 6]])"
"np.concatenate((a, b), axis=None)"
"array([1, 2, 3, 4, 5, 6])"


'array([1, 2, 3, 4, 5, 6])'

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [10]:
# Import pandas library
import pandas as pd
  
# initialize list of lists
"data = [['ram', 10], ['jam', 15], ['sam', 14]]"
  
# Create the pandas DataFrame
"df = pd.DataFrame(data, columns=['Name', 'Age'])"
  
# print dataframe.

"df = pd.DataFrame(data, columns=['Name', 'Age'])"

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [11]:
import datetime
import pandas as pd
 
# initializing date
"test_date = datetime.datetime.strptime(""01-1-2023"", ""%d-%m-%Y"")"
 
# initializing K
K = 41
 
"date_generated = pd.date_range(test_date, periods=K)"
print(date_generated.strftime("%d-%m-%Y"))


NameError: name 'date_generated' is not defined

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [14]:
import pandas as pd
"df = pd.DataFrame(lst, columns =['FName', 'LName', 'Age'],"
                                           dtype = float) 
print(df)

IndentationError: unexpected indent (<ipython-input-14-08cadf840598>, line 3)

In [13]:
"df = pd.DataFrame(lst, columns =['FName', 'LName', 'Age'],"
                                           dtype = float) 
print(df)

IndentationError: unexpected indent (<ipython-input-13-c789e2759eae>, line 2)